<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <VersionPrefix>0.1.0</VersionPrefix>
    <Authors>DXNexus</Authors>
    <RepositoryUrl>https://github.com/rapinoinfeliz/SDRNexus</RepositoryUrl>
  </PropertyGroup>

  <PropertyGroup>
    <SdrSharpSdkDirectory Condition="'$(SdrSharpSdkDirectory)' == '' and '$(SDRSHARP_SDK_DIR)' != ''">$(SDRSHARP_SDK_DIR)</SdrSharpSdkDirectory>
    <SdrSharpSdkDirectory Condition="'$(SdrSharpSdkDirectory)' == ''">$(MSBuildThisFileDirectory).sdk</SdrSharpSdkDirectory>
  </PropertyGroup>
</Project>
